name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  depoy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Use Node 14
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: Install
      run: npm ci
    - name: Build and Deploy
      env:
        NODE_ENV: production
        # This is set automatically by github
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REACT_APP_GA_MEASUREMENT_ID: ${{ secrets.REACT_APP_GA_MEASUREMENT_ID }}
        # PUBLIC_URL: https://gener8or.github.io/gener8or-site/
      run: | 
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/gener8or/gener8or-site.git
          npm run deploy
